# 開発用ベースイメージ
FROM node:20-slim

WORKDIR /app

# パッケージ管理
COPY package.json package-lock.json ./
RUN npm install

# ソースコードのコピー
COPY . .

# Viteなどの開発サーバを起動（0.0.0.0で公開しないとブラウザから見えません）
CMD ["npm", "run", "dev", "--", "--host"]