services:
  # Backend: LiteSpeed + PHP 8.4
  backend:
    build:
      context: ./backend    # backendフォルダを指定
      dockerfile: Dockerfile # さっき作ったファイルを指定

    image: litespeedtech/openlitespeed:1.8.2-lsphp83
    container_name: rising-backend
    ports:
      - "8080:80"
      - "7080:7080"
    volumes:
# 「backend」フォルダそのものを「html」としてマウントする
      - ./backend:/var/www/vhosts/localhost/html
    environment:
      - TZ=Asia/Tokyo
      - ADMIN_PASSWORD=password123
    depends_on:
      - db
    restart: always

  # Frontend: React (Vite) + TypeScript + Tailwind
  frontend:
    user: "node" # rootではなくnodeユーザーで実行させる
    build: ./frontend
    image: node:20-slim
    container_name: rising-frontend
    working_dir: /src
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/src
    tty: true
    stdin_open: true
    command: sh -c "cd react-app && npm install && npm run dev -- --host"

  # Database: MySQL
  db:
    image: mysql:8.0
    container_name: rising-db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: rising_db
      MYSQL_USER: user_name
      MYSQL_PASSWORD: user_password
    volumes:
      - ./mysql_data:/var/lib/mysql
    restart: always