FROM php:8.2-cli

# MySQL接続用ドライバのみインストール
RUN docker-php-ext-install pdo pdo_mysql

WORKDIR /var/www/html

# PHPのビルトインサーバーをポート8080で起動
# 0.0.0.0 で動かさないとDocker外部（ブラウザ）からアクセスできません
CMD ["php", "-S", "0.0.0.0:80", "-t", "/var/www/html"]